global_frame: map
map_topic: "map"
update_frequency: 30.0
publish_frequency: 30.0
static_map: true
track_unknown_space: true
#always_send_full_costmap: true

# plugins for global costmap are in robot folder
