robot_base_frame: base_link

transform_tolerance: 1 #0.5

robot_radius: 0.30
inflater:
  robot_radius: 0.30
  inflation_radius: 1 #0.7 #1.0 #0.3
  cost_scaling_factor: 2.58

# Obstacles are defined in robot folders
