# Planner selection global_planner/GlobalPlanner navfn/NavfnROS
base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

# Recovery behaviors are defined in robot folders

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.5

# Global planner
planner_frequency: 2.0
planner_patience: 5.0
NavfnROS:
  allow_unknown: false  # TODO: investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false
GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.0
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  visualize_potential: false
  cost_factor: 0.55
  neutral_cost: 66
  lethal_cost: 253
  
# Local planner
controller_frequency: 15.0
controller_patience: 5.0
TrajectoryPlannerROS:
  # base vel/accel profile is in robot folders
  # tolerances (defaults)
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: true
  # forward simulation
  sim_time: 2.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 20 #3
  vtheta_samples: 40 #10
  # scoring (defaults)
  meter_scoring: true
  pdist_scale: 8.0
  gdist_scale: 12.0
  occdist_scale: 0.1
  heading_lookahead: 0.325
  heading_scoring_timestep: 0.8
  heading_scoring: true
  dwa: false
  # other
  oscillation_reset_dist: 0.05
  # debug
  publish_cost_grid_pc: false

DWAPlannerROS:
  max_vel_y: 0
  min_vel_y: 0

  xy_goal_tolerance: 0.3
  yaw_goal_tolerance: 0.3

  prune_plan: true

  sim_time: 2.0
  vx_samples: 6
  vy_samples: 1
  vtheta_samples: 20

  path_distance_bias: 32
  goal_distance_bias: 24
  occdist_scale: 0.01

#  max_trans_vel: 0.8
#  min_trans_vel: 0
#  max_rot_vel: 3.2
#  min_rot_vel: 0

# vx_samples: 50
# vy_samples: 0 # The number of samples to use when exploring the y velocity space official default [10]
# vtheta_samples: 80 # [20] The number of samples to use when exploring the theta velocity space
