obstacles:
  observation_sources: base_scan
  base_scan:
    data_type: LaserScan
    topic: base_scan_filtered
    marking: true
    clearing: true
    inf_is_valid: true

    obstacle_range: 3.0
    raytrace_range: 20.0
    
    min_obstacle_height: 0.01
    max_obstacle_height: 1.6
    publish_voxel_map: false
    
    origin_z: 0.0
    z_resolution: 0.2
    z_voxels: 10
    mark_threshold: 3
    expected_update_rate: 0.0

